from ..parameter_panel_support import *


class ParameterPanelConditionalClickRuleParamsMixin:
    _MOUSE_IMAGE_CLICK_PARAMS = {
        '---common_click_params---',
        'button',
        'clicks',
        'interval',
        'image_position_mode',
        'image_offset_selector_tool',
        'image_fixed_offset_x',
        'image_fixed_offset_y',
        'image_random_offset_x',
        'image_random_offset_y',
        'image_click_action',
        'image_enable_auto_release',
        'image_hold_mode',
        'image_hold_duration',
        'image_hold_duration_min',
        'image_hold_duration_max',
    }
    _MOUSE_COLOR_CLICK_PARAMS = {
        'click_position_mode',
        'color_offset_selector_tool',
        'color_fixed_offset_x',
        'color_fixed_offset_y',
        'color_random_offset_x',
        'color_random_offset_y',
        'color_click_button',
        'color_click_clicks',
        'color_click_interval',
        'color_click_action',
        'color_enable_auto_release',
        'color_hold_mode',
        'color_hold_duration',
        'color_hold_duration_min',
        'color_hold_duration_max',
    }
    _MOUSE_TEXT_CLICK_PARAMS = {
        '---common_click_params---',
        'button',
        'clicks',
        'interval',
        'text_position_mode',
        'text_offset_selector_tool',
        'text_fixed_offset_x',
        'text_fixed_offset_y',
        'text_random_offset_x',
        'text_random_offset_y',
        'text_click_action',
        'text_enable_auto_release',
        'text_hold_mode',
        'text_hold_duration',
        'text_hold_duration_min',
        'text_hold_duration_max',
    }
    _MOUSE_COORDINATE_CLICK_PARAMS = {
        '---common_click_params---',
        'button',
        'clicks',
        'interval',
        'coordinate_position_mode',
        'coordinate_offset_selector_tool',
        'coordinate_fixed_offset_x',
        'coordinate_fixed_offset_y',
        'coordinate_random_offset_x',
        'coordinate_random_offset_y',
        'coordinate_click_action',
        'coordinate_enable_auto_release',
        'coordinate_hold_mode',
        'coordinate_hold_duration',
        'coordinate_hold_duration_min',
        'coordinate_hold_duration_max',
    }
    _MOUSE_ELEMENT_CLICK_PARAMS = {
        'element_use_invoke',
        'element_button',
    }
    _FIND_IMAGE_CLICK_PARAMS = {
        '---click_offset---',
        'button',
        'click_action',
        'enable_auto_release',
        'hold_duration',
        'clicks',
        'interval',
        'offset_selector_tool',
        'image_position_mode',
        'fixed_offset_x',
        'fixed_offset_y',
        'random_offset_x',
        'random_offset_y',
    }
    _COORDINATE_CLICK_TASK_PARAMS = {
        '---click_settings---',
        'button',
        'click_action',
        'hold_duration',
        'clicks',
        'interval',
        '---click_offset---',
        'offset_selector_tool',
        'position_mode',
        'fixed_offset_x',
        'fixed_offset_y',
        'random_offset_x',
        'random_offset_y',
    }
